services:
  dockwatch:
    container_name: dockwatch
    image: ghcr.io/notifiarr/dockwatch:v0.6.457
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      docker_network:
        ipv4_address: ${IP_DOCKWATCH}
      socket_proxy:
    ports:
      - "${DOCKWATCH_EXT_PORT}:${DOCKWATCH_INT_PORT}/tcp"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: 999
      DOCKER_HOST: "tcp://socket-proxy:${SOCKET_PROXY_PORT}"
    volumes:
      - "${DOCKERDIR}/appdata/dockwatch/config:/config"
