services:
  filebrowser:
    image: filebrowser/filebrowser:v2.40.2
    container_name: filebrowser
    networks:
      docker_network:
        ipv4_address: ${IP_FILEBROWSER}
    user: ${PUID}:${PGID}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${FILEBROWSER_EXT_PORT}:${FILEBROWSER_INT_PORT}"
    volumes:
      - "${DATADIR}:/srv"
      - "${DOCKERDIR}/appdata/filebrowser/filebrowser.db:/database.db"
      - "${DOCKERDIR}/appdata/filebrowser/.filebrowser.json:/.filebrowser.json"
    environment:
      TZ: ${TZ}
