services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    networks:
      docker_network:
        ipv4_address: ${IP_JELLYFIN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped 
    user: ${PUID}:${PGID}
    ports:
      - "${JELLYFIN_PORT}:${JELLYFIN_PORT}"
    environment:
      UMASK_SET: 022
      TZ: ${TZ}
        #    runtime: nvidia
        #    deploy:
        #      resources:
        #        reservations:
        #          devices:
        #            - driver: nvidia
        #              count: all
        #              capabilities: [gpu]
    volumes:
      - "${DOCKERDIR}/appdata/jellyfin:/config"
      - "${DATADIR}/data/media:/data/media"
