services:
  karakeep-web:
    image: ghcr.io/karakeep-app/karakeep:0.26.0
    restart: unless-stopped
    container_name: karakeep-web
    networks:
      docker_network:
        ipv4_address: ${IP_KARAKEEP_WEB}
    volumes:
      - "${DATADIR}/data/karakeep/web:/data"
    ports:
      - "${KARAKEEP_WEB_EXT_PORT}:${KARAKEEP_WEB_INT_PORT}"
    environment:
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS
      NEXTAUTH_SECRET: ${KARAKEEP_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${KARAKEEP_MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${KARAKEEP_NEXTAUTH_URL}
  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: karakeep-chrome
    networks:
      docker_network:
        ipv4_address: ${IP_KARAKEEP_CHROME}
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.17.1
    restart: unless-stopped
    container_name: karakeep-meilisearch
    networks:
      docker_network:
        ipv4_address: ${IP_KARAKEEP_MEILISEARCH}
    environment:
      NEXTAUTH_SECRET: ${KARAKEEP_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${KARAKEEP_MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${KARAKEEP_NEXTAUTH_URL}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - "${DATADIR}/data/karakeep/meilisearch:/meili_data"
