services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2025.11.16
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - "${DATADIR}/data/media/newmusic:/downloads"
    environment:
      UID: ${PUID}
      GID: ${PGID}
      DEFAULT_THEME: "dark"
      DOWNLOAD_DIRS_INDEXABLE: "true"
      DOWNLOAD_MODE: "sequential"
