services:
  pihole:
    networks:
      docker_network:
        ipv4_address: ${IP_PIHOLE}
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole:2025.11.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_UI_EXT_PORT}:${PIHOLE_UI_INT_PORT}/tcp"
    environment:
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      TZ: ${TZ}
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - '${DOCKERDIR}/appdata/pihole/etc-pihole:/etc/pihole'
      - '${DOCKERDIR}/appdata/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
