services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.26.26
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      docker_network:
        ipv4_address: ${IP_RADARR}
    ports:
      - "${RADARR_PORT}:${RADARR_PORT}"
    volumes:
      - '${DOCKERDIR}/appdata/radarr:/config'
      - '${DATADIR}/data:/data'
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
