services:
  readarr:
    image: hotio/readarr
    container_name: readarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped 
    networks:
      docker_network:
        ipv4_address: ${IP_READARR}
    ports:
      - "${READARR_PORT}:${READARR_PORT}"
    volumes:
      - '${DOCKERDIR}/appdata/readarr:/config'
      - '${DATADIR}/data:/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
