services:
  sabnzbd:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: lscr.io/linuxserver/sabnzbd:5.0.4
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK_SET: 002
    volumes:
      - '${DOCKERDIR}/appdata/sabnzbd/config:/config'
      - '${DATADIR}/data/usenet:/data/usenet'
