services:
  sonarr:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: lscr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    networks:
      docker_network:
        ipv4_address: ${IP_SONARR}
    ports:
      - "${SONARR_PORT}:${SONARR_PORT}"
    volumes:
      - '${DOCKERDIR}/appdata/sonarr:/config'
      - '${DATADIR}/data:/data'
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
