services:
  archivist:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.5.5
    container_name: archivist
    network_mode: "service:gluetun"
    volumes:
      - '${DATADIR}/data/media/josh/youtube:/youtube'
      - '${DATADIR}/data/media/tube-archivist/cache:/cache'
    environment:
      HOST_UID: ${PUID}
      HOST_GID: ${PGID}
      ES_URL: "http://localhost:${TA_ES_PORT}"
      ELASTIC_PASSWORD: ${TA_ELASTIC_PASSWORD}
      REDIS_CON: "redis://${IP_TA_REDIS}:${TA_REDIS_PORT}"
      TA_HOST: ${IP_TA} ${IP_SERVER}
      TA_PORT: ${TA_PORT}
      TA_BACKEND_PORT: ${TA_BACKEND_PORT}
      TA_USERNAME: ${TA_USERNAME}
      TA_PASSWORD: ${TA_PASSWORD}
      TZ: ${TZ}
    depends_on:
      - archivist-es
      - archivist-redis
    healthcheck:
      test: "curl -sf https://example.com || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 60s

  archivist-redis:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: redis
    container_name: archivist-redis
    networks:
      docker_network:
        ipv4_address: ${IP_TA_REDIS}
    volumes:
      - '${DOCKERDIR}/appdata/tube-archivist/redis:/data'
    depends_on:
      - archivist-es

  archivist-es:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: bbilly1/tubearchivist-es:8.18.0
    container_name: archivist-es
    network_mode: "service:gluetun"
    environment:
      ELASTIC_PASSWORD: ${TA_ELASTIC_PASSWORD}
      PGID: ${PGID}
      PUID: ${PUID}
      ES_JAVA_OPTS: "-Xms512m  -Xmx512m"
      xpack.security.enabled: "true"
      discovery.type: "single-node"
      path.repo: "/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - '${DOCKERDIR}/appdata/tube-archivist/elasticsearch:/usr/share/elasticsearch/data'
    healthcheck:
      test: "curl -sf https://example.com || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 60s

